image: alpine

pages:
  script:
  - apk update && apk add doxygen graphviz ttf-freefont texlive-dvi ghostscript graphviz
  - cd docs
  - doxygen Doxyfile
  - mv html/ ../public/
  artifacts:
    paths:
    - public
