image: ubuntu:bionic

pages:
  script:
  - apt update && apt install doxygen ttf-freefont texlive-science ghostscript graphviz
  - cd docs
  - doxygen Doxyfile
  - mv html/ ../public/
  artifacts:
    paths:
    - public
