artifacts:reports:license_scanning
image: ubuntu:bionic
pages:
  script:
  - apt update && apt-get -y install doxygen fonts-freefont-ttf texlive-science ghostscript graphviz
  - cd docs
  - doxygen Doxyfile
  - cp -r html/ ../public/
  artifacts:
    paths:
    - public

